name: Build and Deploy to GitHub Pages

on:
    push:
        branches: ["main"]

    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Setup Pages
              uses: actions/configure-pages@v5
            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Build with Bun
              run: bun build --minify index.html --outdir dist
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v4
              with:
                  path: ./dist

    # Deployment job
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
